from .GA import GA
import sys

class TaskAssignment(object):

    """
    generated by an algorithm [tag_Genetic_Algothm]
    """

    def __init__(self, originalItemList=None):
        self.itemList = originalItemList

    def itemListGeneratedByAlgorithm(self, algorithmName, notFirstTime=0):
        """
        _summary_

        Args:
            algorithmName (_type_): _description_
            firstTime (int, optional): Defaults to 0, means this is the firstTime call; 1- not firstTime.
        """
        if not notFirstTime:
            return 
        if not algorithmName:
            pass
        if algorithmName == 'GA':
            ga_object = GA(self.itemList)
            self.itemList = ga_object.generate(self.itemList)
            print(17, sys._getframe().f_lineno, f'| 1 = {self.itemList}', ) # 2023_0509_2331
            return 
        elif algorithmName == 'PSO':
            return 

    def getItemList(self):
        print(25, sys._getframe().f_lineno, f'| 1 = {self.itemList}', ) # 2023_0509_23322
        return self.itemList
        
